### ISSUE TITLE
MeasureObjectIntensity Multichannel - Error: too many indices for array

### ISSUE THREAD

**Issue by hartlandj** [BodenmillerGroup/ImcPluginsCP#14]
Indexerror:too many indices for array

What's the max? I will try to split to run a couple of modules after each other and see if that works.

**Comment by hartlandj** [comment]
Nope, didn't work - I'm running it on the ZMB server, maybe a problem with that.

**Comment by votti** [comment]
The issue was that the wrong number of channels were specified in the module. So no error in the module itself.

**Comment by arcolombo** [comment]
How can we double check the number of channels  to input into the MeasureObjectIntensity Multichannel?  my panel.csv used 32 channels,  but I am getting this error.  So is there a way I can check how many channels are in the input tiffs ?

**Comment by votti** [comment]
Hi,
One way is to open an image in ImageJ and check the channel number. If you made an analysis stack using our pipeline you can also check any of the `*_full.csv` that is generated alongside the `*_full.tiff`files, which lists all the channels of the corresponding tiffs.
Does this helps!
