### ISSUE TITLE
Question about modifying preferences of CellProfiler to point toward ImcPluginsCP

### ISSUE THREAD

**Issue by arcolombo** [BodenmillerGroup/ImcPluginsCP#18]
Hello.  I am a new user, and have installed Anaconda, Jupyter, and CellProfiler.

 It is not exactly clear how to modify CellProfiler preferences.  Should I just copy the imcPluginsCP to the CellProfiler plugins directory, and re-install CellProfiler?   

Thank you again very much,
Sincerely Yours,

**Comment by votti** [comment]
Hi,

So:
1) Download/clone the git repository: 
Currently for stable use I still recommend CellProfiller 2.2.0: in this case make sure to have either the `master` or the `develop-cp2` branch
If you want to try CellProfiler3, use the `develop-cp3` branch
2) Start CellProfiller
3) Within CellProfiller: File -> Preferences -> CellProfiller plugins directory
Set this to the 'plugins' folder of this repository, so something like `yourpath/ImcPluginsCP/plugins'
4) Restart CellProfiller

5) The plugins should now work

Note that for saving images for ilastik, I am using the `tifffile` library, which needs to be installed in the python of the conda environment that you are using for Cellprofiller.
Does this make sense?

I hope to find time to overhaul and improve the documentation soon, so I am actually happy to see where improvement is needed.

**Comment by arcolombo** [comment]
to start CellProfiler, are you referring to CellProfiler-Analyst? the interactive software?  I do not have the CPA installed.  thank you again.

**Comment by votti** [comment]
No, I am refering to the normal `CellProfiller` - I never tried the CellProfiller analyst.

Usually the CellProfiller GUI can be started from the terminal by writing:
a) `cellprofiller`
b): `python -m cellprofiller'

**Comment by arcolombo** [comment]
okay this makes sense we can close this issue.  the documentation is OK.  This issue arose because my CellProfiler was not running correctly, so I was not able to find the "preferences" tab.   closing this out.  thank you very much
