### ISSUE TITLE
MeasureObjectIntensityMultichannel and MeasureImageIntensityMultichannel have different indexing

### ISSUE THREAD

**Issue by votti** [BodenmillerGroup/ImcPluginsCP#19]
I noticed that these two modules actually do the channel indexing differently:
`MeasureObjectIntensityMultichannel` uses 1 based indexing for the channel number:
https://github.com/BodenmillerGroup/ImcPluginsCP/blob/e0f15c0adeabd73d9a13f281a160e07652cffda1/plugins/measureobjectintensitymultichannel.py#L483

`MeasureImageIntensityMultichannel` uses 0 based indexing for the channel number:
https://github.com/BodenmillerGroup/ImcPluginsCP/blob/e0f15c0adeabd73d9a13f281a160e07652cffda1/plugins/measureimageintensitymultichannel.py#L305

This needs to be fixed!

**Comment by votti** [comment]
I will use the 1 based indexing for both, as measure object intensity was the far more used module, so I will break less compatibility.

**Comment by arcolombo** [comment]
what is the benefit of using "MeasureObjectIntensityMultichannel" ? is it beneficial to run the module "MeasureObjectIntensityMultichannel" after the segmenation mask has been created, but before identifying phenograph via Histocat?  Does the "measureObjectIntensity" module enhance the mask to improve downstream analysis?

Thank you again,
Ac

**Comment by votti** [comment]
This issue is addressed in commit: ddbefb1468c050d2cccb7fbc3f847e9c1eaa42f9
