### ISSUE TITLE
Correct spillover matrix or TIFF image used for CP3 spillover correction

### ISSUE THREAD

**Issue by arcolombo** [BodenmillerGroup/ImcPluginsCP#27]
Hi.   I have a spillover matrix in terms of quantitative matrix.   I am not sure how to integrate this in the CP3 spillover correction module.  Do I need a TIFF image based on the spillover corrected image to import into CP3 spillover correction module?  suggestions?

**Comment by votti** [comment]
Hi,
I try to document how to do this in the new description of the segmentation pipeline: https://github.com/BodenmillerGroup/ImcSegmentationPipeline/blob/development/scripts/imc_preprocessing.ipynb
Section **3_measure_mask_compensation** - can you check if this would make sense to you?

Specifically a `.csv` based spillover matrix needs to be adapted to the channels  actually used in an image and saved to a `.tiff` for cellprofiler, which can be done with this script from the compensation paper: https://github.com/BodenmillerGroup/cyTOFcompensation/blob/master/scripts/imc_adaptsm.Rmd
An example spillover matrix can be found here: https://github.com/BodenmillerGroup/ImcSegmentationPipeline/tree/development/config
(note that you need to generate a custom matrix for the isotope lots you are using to get valid results: https://docs.google.com/document/d/195eViUqHoYRKrkoy_NkIdJPmyx1-OuDaSjiWQBy4weA/edit?usp=sharing )
