### ISSUE TITLE
Rename plugin names to not include whitespaces

### ISSUE THREAD

**Issue by jwindhager** [BodenmillerGroup/ImcPluginsCP#36]
IMHO, it would be worth considering renaming the modules (e.g. "MeasureObjectIntensity Multichannel") to not contain whitespaces (e.g. "MeasureObjectIntensityMultichannel"). This would make it easier to work with the output CSV files in programming languages such as R, which don't allow whitespaces in variable names (or, in the case of R, require special treatment, e.g. for element names of a named list).

**Comment by votti** [comment]
That is actually a good point!

However, renaming the modules will break all existing pipelines.
I would suggest to:
1) In a transition period: make a copy of the module with the old `module_name`, that will raise a 'deprecated' warning and contains clear documentation that this will be removed within the next releases and that the renamed module should be used in the future.
2) Fix the `module_name` attributes to not include whitespaces.

Until this is done, I would recommend to set the `check.names=TRUE` option in `fread`/`read.table` (or whatever funciton is used to load the data), which should convert all names to valid ones.

**Comment by votti** [comment]
Above could also be achieved by changing the `module_name` in the main class. Then simply a subclass with the old name could be added together with a deprecation warning. This would keep the backwards compatibility while minimizing code duplication.

**Comment by votti** [comment]
I just found that `upgrade_settings` also allows to change module names. I think that would automatically fix the naming once the pipline is re-saved.

To do this:
- change the module name 
- make a subclass with the old module name and an 'upgrade_settings'  function to fix the name to the new name.

**Comment by votti** [comment]
This is now implemented in the CP4 plugins branch.
