### ISSUE TITLE
Could not run pipeline

### ISSUE THREAD

**Issue by kelvinlee760948065** [BodenmillerGroup/ImcPluginsCP#39]
When I try to adapt my .tiff files into the ImcPluginsCP, error happens as pictures shown:
![image](https://user-images.githubusercontent.com/71078929/93604622-35eab000-f9f8-11ea-8e7d-116c42390aeb.png)
![image](https://user-images.githubusercontent.com/71078929/93604663-44d16280-f9f8-11ea-90c9-80c896b26fef.png)

**Comment by votti** [comment]
Hi!
Is this an issue for: https://github.com/BodenmillerGroup/ImcSegmentationPipeline ?
If so, please file it there.

Anyways: Cellprofiler identifies images based on their name. The rules how to identify which image is which is defined in the `Metadata` and `NamesAndTypes` section.
If you are using a custom naming scheme, you need to adapt these sections. This is standard CellProfiler behaviour.

Hope this helps!
