### ISSUE TITLE
usage on CellProfiler 4

### ISSUE THREAD

**Issue by SBata** [BodenmillerGroup/ImcPluginsCP#40]
moved the issue on the CP github
https://github.com/CellProfiler/CellProfiler/issues/4298#issue-730049116
I thought it would be more appropriate there

hi there

I downloaded the plugin folder and added the path to the CP 4 plugins. 
however, when I try to load a pipeline that contains the `MeasureObjectIntensity Multichannel` I get the following error:

```
Error while loading MeasureObjectIntensity Multichannel: Could not find the MeasureObjectIntensity Multichannel module
Do you want to stop processing?

```
any suggestions?

**Comment by SBata** [comment]
as per comment on the CP github (https://github.com/CellProfiler/CellProfiler/issues/4298) I am re-opening this

**Comment by votti** [comment]
Hi!

Currently the main branch is still CP3 - but I have already a fully working branch for cellprofiler 4:
https://github.com/BodenmillerGroup/ImcPluginsCP/tree/develop-cp4

Please download this version of the plugins.

Let me know if you  run into any issues!

**Comment by SBata** [comment]
the CP4 modules work well, thank you.
in case anyone else will use them:
1. change the path
2. restart CP
3. enjoy

**Comment by SBata** [comment]
the CP4 modules work well, thank you.
in case anyone else will use them:

1. change the path
2. restart CP
3. enjoy

**Comment by votti** [comment]
Glad it works!
I pinned the issue so it also may help others.

Please let me know if you find any issues.

**Comment by 908166479** [comment]
Hi! @votti @SBata 
    I launch CellProfiler via source code with parameter --plugins-directory.
    It seems everything well at the beginning.
    But when I try to import pipeline from file '2_segment_ilastik.cppipe'
    I get the following error:
![image](https://user-images.githubusercontent.com/26714289/97824226-5051c200-1cf6-11eb-9cb8-b3312fc572f1.png)

![image](https://user-images.githubusercontent.com/26714289/97824449-ec7bc900-1cf6-11eb-822b-9f92ef2cc916.png)

**Comment by votti** [comment]
Hi!
This is an issue about the ImcSegmentationPipeline?
Are you sure you are using CellProfiler 3 with Cellprofiler 3 compatible plugins (as metioned in the README, https://github.com/BodenmillerGroup/ImcPluginsCP/tree/master-cp3) and not the default `master` branch which requires now CP4?

I am only limited available this week as I am in holidays.

Best, Vito

**Comment by PPPparry** [comment]
> Hi!
> This is an issue about the ImcSegmentationPipeline?
> Are you sure you are using CellProfiler 3 with Cellprofiler 3 compatible plugins (as metioned in the README, https://github.com/BodenmillerGroup/ImcPluginsCP/tree/master-cp3) and not the default `master` branch which requires now CP4?
> 
> I am only limited available this week as I am in holidays.
> 
> Best, Vito

Thanks for your suggestion, Vito.
Well, I was using CellProfiler 4 with CellProfiler 3 plugins because I got some strange errors when I setup Cellprofiler3 from source code.
Back to this question, the reason why I got that error seems that I missed the parameter '--pipeline'. But I got the following error after I added this parameter:
![image](https://user-images.githubusercontent.com/26714289/97969533-27672500-1dfb-11eb-8dbc-85b47c3daf9e.png)
and I am trying to solve it.

Anyway, have a nice vacation.

**Comment by votti** [comment]
Hi,
Cellprofiller 4 does only work with Cellprofiller 4 plugins (same for
cellprofiller 3 and CP3 plugins).

If you use the Gui it should not be necessary to use the command line flags.
If you want to use cellprofiller 4, you can try the example CP4 pipelines
from this branch:
https://github.com/BodenmillerGroup/ImcSegmentationPipeline/tree/imctools2

Best
