### ISSUE TITLE
Error while loading Smooth Multichannel: Could not find the Smooth Multichannel module

### ISSUE THREAD

**Issue by luglilab** [BodenmillerGroup/ImcPluginsCP#51]
Hello,

when we try to import pipeline 1_prepare_ilastik.cppipe on CellProfiler version 3.1.9 we get the following error:

Error while loading Smooth Multichannel: Could not find the Smooth Multichannel module
Do you want to stop processing?

Module settings:
	Ilastik
	IlastikFil
	Remove single hot pixels
	Yes
	16.0
	0.1
	Yes
	3
	50.0
	Yes

If we press continue processing the pipeline is not loaded, could you explain how to install Smooth Multichannel plugin? 

Best regards

**Comment by nilseling** [comment]
Hi @luglilab 

did you install the plugins as described in the README:

```
For installation copy the folder to a local directory, modify the CellProfiler Preferences in the GUI to the plugin folder (PATHTO/ImcPluginsCP/plugins) and restart cellprofiler.
```

A few more details: 

1. you clone the `master-cp3` branch of the `ImcPluginsCP` repository 
2. open CellProfiler > Preferences, and select the local folder of `PATHTO/ImcPluginsCP/plugins` under `CellProfiler plugins repository`
3. close and open CellProfiler before importing the pipeline

Does that work for you?

**Comment by luglilab** [comment]
Hi @nilseling,

I install cellprofiler using this tutorial https://github.com/CellProfiler/CellProfiler/wiki/Source-installation-%28OS-X-and-macOS%29 

I had some problems at begin because in the new version of brew  "brew cask install java" doesn't work but looking around I found a solution "brew install java" now it seems to work in correct way. 

Later I got this message "This program needs access to the screen. Please run with a Framework build of python, and only when you are logged in on the main display of your Mac" but at the end execute this command:

pythonw $PATH/cellprofiler where path is were cellprofiler is installed it seems works. 

Simone

**Comment by nilseling** [comment]
Alright, that's how you installed CellProfiler. But did you install the ImcPluginsCP? These are custom made plugins for IMC analysis (they are not contained in the base CellProfiler version)and need to be loaded into CellProfiler as the README and my previous post suggest.

**Comment by luglilab** [comment]
Dear @nilseling ,

thank you I was able to reproduce the analysis in the tutorial. 

Simone

**Comment by nilseling** [comment]
That's great to hear! I'm glad it worked out.
