### ISSUE TITLE
IMC - CorrectSpilloverApply

### ISSUE THREAD

**Issue by jsymington** [BodenmillerGroup/ImcPluginsCP#52]
Hi all,

I am having an issue with the CorrectSpilloverApply module in cell profiler. I have generated my matrix successfully. I am now trying to run the module on my multi channel images alongside the matrix 32 bit TIFF generated in R.

I am getting the following error:

Error while processing CorrectSpilloverApply:
not enough values to unpack (expected 3, got 2)

Does anyone know how I can go about fixing this?

Thanks again
Jake

**Comment by nilseling** [comment]
We are currently not supporting the use of `ImcPluginsCP` for spillover correction anymore. Please have a look here how to perform spillover correction with the newest pipeline: https://bodenmillergroup.github.io/IMCDataAnalysis/spillover-correction.html So unless anyone else knows how to fix it, I would recommend switching to the maintained workflow.

**Comment by jsymington** [comment]
I see – I will look to move my analysis over to this workflow.

Jake
